"use strict";

/**
 * 🌌 SORA AI PROMPTS SSOT (v2 / 2026-02)
 * - ここが唯一の正本
 * - 各チャンネルは「出力形式」だけが差分
 */

const { SYSTEM_COMMON, STYLE_COMMON } = require("./common");
const {
  SYSTEM_BLUEPRINT_LIGHT,
  USER_GUIDE_BLUEPRINT_LIGHT,
  RULES_BLUEPRINT_LIGHT_PROSE,
  BLUEPRINT_LIGHT_USER_PROMPT_PREFIX,
} = require("./blueprint_light");
const {
  SORA_AI_USER_GUIDE_ITEM,
  SORA_AI_USER_GUIDE_SORA,
  SORA_AI_USER_GUIDE_PERSONAL,
  SORA_AI_USER_GUIDE_BLOG,
} = require("./today_sora");

const SORA_AI_SYSTEM_PROMPT_COMMON = `${SYSTEM_COMMON}\n\n${STYLE_COMMON}`.trim();

module.exports = Object.freeze({
  SORA_AI_SYSTEM_PROMPT_COMMON,
  SORA_AI_STYLE_GUIDE_COMMON: STYLE_COMMON,
  SORA_AI_SYSTEM_PROMPT_BLUEPRINT_LIGHT: SYSTEM_BLUEPRINT_LIGHT,
  SORA_AI_USER_GUIDE_SORA,
  SORA_AI_USER_GUIDE_ITEM,
  SORA_AI_USER_GUIDE_PERSONAL,
  SORA_AI_USER_GUIDE_BLOG,
  SORA_AI_USER_GUIDE_BLUEPRINT_LIGHT: USER_GUIDE_BLUEPRINT_LIGHT,
  RULES_BLUEPRINT_LIGHT_PROSE,
  BLUEPRINT_LIGHT_USER_PROMPT_PREFIX,
});
