"use strict";

const APP_SCHEMA_VERSION = "1.0.0";
const STORY_SCHEMA_VERSION = "1.0.0";
const NATAL_SCHEMA_VERSION = "1.0.0";
const LINE_USER_SCHEMA_VERSION = "1.0.0";
const RELATION_SCHEMA_VERSION = "1.1.0";
const RELATION_VIEW_SCHEMA_VERSION = "relation_view_v1";
const DICTIONARIES_BUNDLE_SCHEMA_VERSION = "dictionaries.bundle.v1";

module.exports = {
  APP_SCHEMA_VERSION,
  DICTIONARIES_BUNDLE_SCHEMA_VERSION,
  LINE_USER_SCHEMA_VERSION,
  NATAL_SCHEMA_VERSION,
  RELATION_SCHEMA_VERSION,
  RELATION_VIEW_SCHEMA_VERSION,
  STORY_SCHEMA_VERSION,
};
