"use strict";

/**
 * 🌌 SORA AI PROMPTS SSOT (v2 / 2026-02)
 * - ここが唯一の正本
 * - 各チャンネルは「出力形式」だけが差分
 */

const { SYSTEM_COMMON, STYLE_COMMON } = require("../common");
const {
  SYSTEM_BLUEPRINT_LIGHT,
  USER_GUIDE_BLUEPRINT_LIGHT,
  RULES_BLUEPRINT_LIGHT_PROSE,
  BLUEPRINT_LIGHT_USER_PROMPT_PREFIX,
  BLUEPRINT_LIGHT_USER_PROMPT_TEMPLATE,
  BLUEPRINT_LIGHT_V2_USER_PROMPT_TEMPLATE,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_CORE,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_MAP,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_OBS,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_ROLES,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_ASPECTS,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_CLOSING,
} = require("../pdf/blueprint/light");
const {
  SORA_AI_USER_GUIDE_ITEM,
  SORA_AI_USER_GUIDE_SORA,
  SORA_AI_USER_GUIDE_PERSONAL,
} = require("./today_sora");
const {
  SORA_AI_USER_GUIDE_IG_CAROUSEL_CAPTION,
  SORA_AI_USER_GUIDE_IG_CAROUSEL_OBSERVATION,
  SORA_AI_USER_GUIDE_IG_RESONANCE,
  SORA_AI_USER_GUIDE_IG_OBSERVATION,
  SORA_AI_USER_GUIDE_IG_SKY_OVERVIEW,
  SORA_AI_USER_GUIDE_IG_TSUKIJI_STRUCTURE,
  SORA_AI_USER_GUIDE_IG_MOON,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_CAPTION,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_PLACEMENT,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_SUN_MOON,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_RESONANCE,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_AIR,
} = require("../sns/instagram");
const {
  SORA_AI_PUBLIC_IG_STORY_COMMON,
  SORA_AI_USER_GUIDE_IG_STORY_TODAY,
  SORA_AI_USER_GUIDE_IG_STORY_RESONANCE,
  SORA_AI_USER_GUIDE_IG_STORY_TOMORROW,
} = require("../sns/instagram/story");

const SORA_AI_SYSTEM_PROMPT_COMMON = `${SYSTEM_COMMON}\n\n${STYLE_COMMON}`.trim();

module.exports = Object.freeze({
  SORA_AI_SYSTEM_PROMPT_COMMON,
  SORA_AI_STYLE_GUIDE_COMMON: STYLE_COMMON,
  SORA_AI_SYSTEM_PROMPT_BLUEPRINT_LIGHT: SYSTEM_BLUEPRINT_LIGHT,
  SORA_AI_USER_GUIDE_SORA,
  SORA_AI_USER_GUIDE_ITEM,
  SORA_AI_USER_GUIDE_PERSONAL,
  SORA_AI_USER_GUIDE_IG_RESONANCE,
  SORA_AI_USER_GUIDE_IG_OBSERVATION,
  SORA_AI_USER_GUIDE_IG_SKY_OVERVIEW,
  SORA_AI_USER_GUIDE_IG_TSUKIJI_STRUCTURE,
  SORA_AI_USER_GUIDE_IG_MOON,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_CAPTION,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_PLACEMENT,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_SUN_MOON,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_RESONANCE,
  SORA_AI_USER_GUIDE_IG_MOON_EVENT_AIR,
  SORA_AI_PUBLIC_IG_STORY_COMMON,
  SORA_AI_USER_GUIDE_IG_STORY_TODAY,
  SORA_AI_USER_GUIDE_IG_STORY_RESONANCE,
  SORA_AI_USER_GUIDE_IG_STORY_TOMORROW,
  SORA_AI_USER_GUIDE_IG_CAROUSEL_CAPTION,
  SORA_AI_USER_GUIDE_IG_CAROUSEL_OBSERVATION,
  SORA_AI_USER_GUIDE_BLUEPRINT_LIGHT: USER_GUIDE_BLUEPRINT_LIGHT,
  RULES_BLUEPRINT_LIGHT_PROSE,
  BLUEPRINT_LIGHT_USER_PROMPT_PREFIX,
  BLUEPRINT_LIGHT_USER_PROMPT_TEMPLATE,
  BLUEPRINT_LIGHT_V2_USER_PROMPT_TEMPLATE,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_CORE,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_MAP,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_OBS,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_ROLES,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_ASPECTS,
  BLUEPRINT_LIGHT_V2_SEGMENT_PROMPT_CLOSING,
});
