"use strict";

const PRESETS = {
  ig: {
    sky_overview: {
      outputType: "plain_text",
      minChars: 80,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    observation: {
      outputType: "plain_text",
      minChars: 10,
      maxChars: 22,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    moon: {
      outputType: "plain_text",
      minChars: 100,
      maxChars: 220,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    resonance: {
      outputType: "plain_text",
      minChars: 120,
      maxChars: 200,
      sentenceCount: { min: 3, max: 4 },
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    carousel_caption: {
      outputType: "plain_text",
      minChars: 100,
      maxChars: 220,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    carousel_observation: {
      outputType: "plain_text",
      minChars: 30,
      maxChars: 70,
      lineCount: { min: 2, reason: "need_two_lines" },
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["normalize_observation_lines"],
    },
    tsukiji_structure: {
      outputType: "plain_text",
      minChars: 10,
      maxChars: 24,
      mustStartWith: "構造：",
      prefixReason: "no_prefix",
      disallowNewlines: true,
      newlineReason: "has_newline",
      forbiddenTerms: ["あなた", "今日", "本日", "今"],
      forbiddenTermReasons: {
        "あなた": "has_you",
        "今日": "has_today",
        "本日": "has_today",
        "今": "has_today",
      },
      normalizeRules: ["trim"],
    },
    moon_event_placement: {
      outputType: "plain_text",
      minChars: 120,
      maxChars: 180,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    moon_event_sun_moon: {
      outputType: "plain_text",
      minChars: 120,
      maxChars: 180,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    moon_event_resonance: {
      outputType: "plain_text",
      minChars: 120,
      maxChars: 180,
      forbiddenTerms: ["あなた", "太陽"],
      forbiddenTermReasons: { "あなた": "has_you", "太陽": "has_sun" },
      normalizeRules: ["collapse_spaces"],
    },
    moon_event_air: {
      outputType: "plain_text",
      minChars: 120,
      maxChars: 300,
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["collapse_spaces"],
    },
    story_today: {
      outputType: "plain_text",
      minChars: 45,
      maxChars: 100,
      charCountMode: "no_newlines",
      questionCount: { max: 1, reason: "too_many_questions" },
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
    story_resonance: {
      outputType: "plain_text",
      minChars: 60,
      maxChars: 130,
      charCountMode: "no_newlines",
      questionCount: { max: 1, reason: "too_many_questions" },
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
    story_tomorrow: {
      outputType: "plain_text",
      minChars: 70,
      maxChars: 150,
      charCountMode: "no_newlines",
      questionCount: { max: 1, reason: "too_many_questions" },
      forbiddenTerms: ["あなた"],
      forbiddenTermReasons: { "あなた": "has_you" },
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
  },
  x: {
    base: {
      outputType: "plain_text",
      maxChars: 180,
      normalizeRules: ["format_x_text"],
      repairRules: ["trim_hashtags"],
      xFormat: { normalizeSpaces: true },
      hashtagRules: { maxHashtags: null, trimHashtags: true },
    },
  },
  pdf: {
    blueprint_v2: {
      outputType: "json",
      limitsRef: "LIMITS_V2",
    },
  },
  relation: {
    prompt_limits: {
      outputType: "json",
      limitsRef: "RELATION_PROMPT_LIMITS",
    },
  },
};

module.exports = { PRESETS };
