"use strict";

const PRESETS = {
  ig: {
    sky_overview: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 80,
      normalizeRules: ["collapse_spaces"],
    },
    observation: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 10,
      maxChars: 22,
      normalizeRules: ["collapse_spaces"],
    },
    moon: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 70,
      maxChars: 110,
      normalizeRules: ["collapse_spaces"],
    },
    moon_night: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 50,
      maxChars: 110,
      normalizeRules: ["collapse_spaces"],
    },
    moon_night_caption: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 160,
      maxChars: 320,
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "trim"],
    },
    hashtags: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 5,
      maxChars: 120,
      normalizeRules: ["collapse_spaces"],
    },
    resonance: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 120,
      maxChars: 200,
      normalizeRules: ["collapse_spaces"],
    },
    resonance_split: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 60,
      maxChars: 140,
      normalizeRules: ["collapse_spaces"],
    },
    resonance_caption: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 240,
      maxChars: 320,
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "trim"],
    },
    carousel_caption: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 100,
      maxChars: 220,
      normalizeRules: ["collapse_spaces"],
    },
    carousel_observation: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 30,
      maxChars: 70,
      normalizeRules: ["normalize_observation_lines"],
    },
    monthly_caption: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 120,
      maxChars: 800,
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "trim"],
    },
    tsukiji_structure: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 10,
      maxChars: 24,
      normalizeRules: ["trim"],
    },
    moon_event_placement: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 120,
      maxChars: 180,
      normalizeRules: ["collapse_spaces"],
    },
    moon_event_sun_moon: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 120,
      maxChars: 180,
      normalizeRules: ["collapse_spaces"],
    },
    moon_event_resonance: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 120,
      maxChars: 180,
      normalizeRules: ["collapse_spaces"],
    },
    moon_event_air: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 120,
      maxChars: 300,
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
    moon_event_caption: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 180,
      maxChars: 260,
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "trim"],
    },
    story_today: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 45,
      maxChars: 100,
      charCountMode: "no_newlines",
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
    story_resonance: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 60,
      maxChars: 180,
      charCountMode: "no_newlines",
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
    story_tomorrow: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 70,
      maxChars: 150,
      charCountMode: "no_newlines",
      normalizeRules: ["normalize_newlines", "collapse_inline_spaces", "collapse_blank_lines", "trim"],
    },
  },
  x: {
    base: {
      outputType: "plain_text",
      allowEmpty: true,
      minChars: 1,
      maxChars: 180,
      normalizeRules: ["format_x_text"],
      repairRules: ["trim_hashtags"],
      xFormat: { normalizeSpaces: true },
      hashtagRules: { maxHashtags: null, trimHashtags: true },
    },
  },
  pdf: {
    blueprint_v2: {
      outputType: "json",
      limitsRef: "LIMITS_V2",
    },
  },
  relation: {
    prompt_limits: {
      outputType: "json",
      limitsRef: "RELATION_PROMPT_LIMITS",
    },
  },
};

module.exports = { PRESETS };
